/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-08-12 23:50:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Gallery Iksun</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("    <script src=\"script/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("    <script src=\"script/index.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div id=\"main\">\r\n");
      out.write("            <div class=\"page1\">\r\n");
      out.write("                <header>\r\n");
      out.write("                    <h1><a href=\"index.jsp\"><img src=\"img/header.png\" alt=\"갤러리익선\"></a></h1>\r\n");
      out.write("                    <nav>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Gallery</a>\r\n");
      out.write("                                <ul class=\"sub\">\r\n");
      out.write("                                    <li><a href=\"introduce.jsp\">Gallery Iksun 소개</a></li>\r\n");
      out.write("                                    <li><a href=\"introduceArtists.jsp\">작가별 보기</a></li>\r\n");
      out.write("                              <!--  <li><a href=\"thema.jsp\">테마별 보기</a></li>  -->\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"shop.jsp\">미술품 구매</a>\r\n");
      out.write("                                <ul class=\"sub\">\r\n");
      out.write("                                    <li><a href=\"shop.jsp\">원화 구입</a></li>\r\n");
      out.write("                                    <li><a href=\"wishlist.jsp\">장바구니</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"community.jsp\">커뮤니티</a>\r\n");
      out.write("                                <!-- <ul class=\"sub\">\r\n");
      out.write("                                    <li><a href=\"community.jsp\">게시판</a></li>\r\n");
      out.write("                                </ul> -->\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"mypage.jsp\">마이페이지</a>\r\n");
      out.write("                                <ul class=\"sub\">\r\n");
      out.write("                                    <li><a href=\"myorder.jsp\">주문확인</a></li>\r\n");
      out.write("                                    <li><a href=\"mypage.jsp\">개인정보확인</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <div class=\"right\">\r\n");
      out.write("                        <a href=\"signIn.jsp\">로그인</a>\r\n");
      out.write("                        <a href=\"signUp.jsp\">회원가입</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\"></div>\r\n");
      out.write("                </header>\r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"s1\"></li>\r\n");
      out.write("                        <li class=\"s2\"></li>\r\n");
      out.write("                        <li class=\"s3\"></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"goshop\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            구매 바로가기<br>\r\n");
      out.write("                            >>>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"page2\">\r\n");
      out.write("                <div class=\"gall\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h1>Best Collection</h1>\r\n");
      out.write("                        <p></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pics\">\r\n");
      out.write("                        <div class=\"pic1\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <img src=\"img/phj58-50.jpg\" alt=\"혜진\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pic2\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <img src=\"img/jkh35-33.jpg\" alt=\"소윤\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pic3\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <img src=\"img/kyj-317786.jpg\" alt=\"온일\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"desc\">\r\n");
      out.write("                        <div class=\"desc1\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"p_artist\">혜진 <span>박호자</span></p>\r\n");
      out.write("                                <p class=\"p_title\">어머니의 봄날1</p>\r\n");
      out.write("                                <p class=\"p_price\">가격: </p>\r\n");
      out.write("                                <p class=\"p_size\">크기: </p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"desc2\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"p_artist\">소윤 <span>정경화</span></p>\r\n");
      out.write("                                <p class=\"p_title\">웃는 고양이</p>\r\n");
      out.write("                                <p class=\"p_price\">가격: </p>\r\n");
      out.write("                                <p class=\"p_size\">크기: </p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"desc3\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"p_artist\">온일 <span>김용재</span></p>\r\n");
      out.write("                                <p class=\"p_title\">나팔꽃1</p>\r\n");
      out.write("                                <p class=\"p_price\">가격: </p>\r\n");
      out.write("                                <p class=\"p_size\">크기: </p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- <div class=\"more\">\r\n");
      out.write("                        <a href=\"#\"><h4>더 많은 작품 보기</h4></a>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <footer>\r\n");
      out.write("                    <div class=\"flogo\">\r\n");
      out.write("                        <h1><a href=\"index.jsp\"><img src=\"img/footer.png\" alt=\"갤러리익선\"></a></h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fcopy\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"gallery.jsp\">회사소개</a></li>\r\n");
      out.write("                            <li><a href=\"privacyPolicy.jsp\">개인정보 처리방침</a></li>\r\n");
      out.write("                            <li class=\"last\"><a href=\"termsUse.jsp\">이용약관</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>Copyright(c) Gallery Iksun. All rights reserved.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fsns\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </footer>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        window.addEventListener(\"wheel\",function(e){    //슬라이드바 없애고 고정창이 움직이지 않게 하는 함수\r\n");
      out.write("            e.preventDefault(); //화면의 스크롤기능 제거 (그런데 이것만 가지고는 구글 브라우저가 가진 패시브모드 발동해서 이게 안먹힘)\r\n");
      out.write("        },{passive:false});     //브라우저의 패시브기능 제거\r\n");
      out.write("        var wrap=document.getElementById(\"wrap\");\r\n");
      out.write("        var posY=0;             //지금 현재 보여주고있는 페이지의 위치\r\n");
      out.write("        wrap.addEventListener(\"wheel\",function(e){\r\n");
      out.write("            if($(\"#main\").is(\":animated\")){\r\n");
      out.write("                console.log(\"1\");\r\n");
      out.write("                return; //밑에 실행하지말고 그냥 끝내버리라는 뜻\r\n");
      out.write("            }\r\n");
      out.write("            move(e);\r\n");
      out.write("        });\r\n");
      out.write("        function move(e){\r\n");
      out.write("            console.log(e.deltaY+\"1111\");\r\n");
      out.write("            if(e.deltaY > 0){\r\n");
      out.write("                posY -= 100;\r\n");
      out.write("            }else if(e.deltaY < 0){\r\n");
      out.write("                posY += 100;\r\n");
      out.write("            }\r\n");
      out.write("            if(posY>0){\r\n");
      out.write("                posY=0;\r\n");
      out.write("            }\r\n");
      out.write("            if(posY<-100){\r\n");
      out.write("                posY=-100;\r\n");
      out.write("            }\r\n");
      out.write("            console.log(posY);\r\n");
      out.write("            $(\"#main\").animate({\"top\":posY+\"%\"},1000);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
