/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-08-12 23:53:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduce_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Gallery Iksun 소개</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/introduce.css\">\r\n");
      out.write("  <script src=\"script/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("  <script src=\"script/header.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <header>\r\n");
      out.write("    <h1><a href=\"index.jsp\"><img src=\"img/header.png\" alt=\"갤러리익선\"></a></h1>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#\">Gallery</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"introduce.jsp\">Gallery Iksun 소개</a></li>\r\n");
      out.write("                    <li><a href=\"introduceArtists.jsp\">작가별 보기</a></li>\r\n");
      out.write("                    <li><a href=\"thema.jsp\">테마별 보기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"shop.jsp\">미술품 구매</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"shop.jsp\">원화 구입</a></li>\r\n");
      out.write("                    <li><a href=\"wishlist.jsp\">장바구니</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"community.jsp\">커뮤니티</a>\r\n");
      out.write("                <!-- <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"community.jsp\">게시판</a></li>\r\n");
      out.write("                </ul> -->\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"mypage.jsp\">마이페이지</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"myorder.jsp\">주문확인</a></li>\r\n");
      out.write("                    <li><a href=\"mypage.jsp\">개인정보확인</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"right\">\r\n");
      out.write("      <a href=\"signIn.jsp\">로그인</a>\r\n");
      out.write("      <a href=\"signUp.jsp\">회원가입</a>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div class=\"bg\"></div>\r\n");
      out.write("</header>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"contents\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cont1\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"txt\">\r\n");
      out.write("        <h1>01</h1>\r\n");
      out.write("\r\n");
      out.write("        <h2>아름다움을 넘어서 미술품이\r\n");
      out.write("          <br>좋은 재테크가 되는 환경을 구축합니다.\r\n");
      out.write("        </h2>\r\n");
      out.write("        <p>아름다운 미술품은 생활의 여유와 내면의 평화를 줍니다.\r\n");
      out.write("          <br>그러나 많은 사람들은 경제적인 이유로 미술품을 쉽게 구입하는 것을 망설입니다.\r\n");
      out.write("          <br>갤러리K에서 수준 높은 작품을 안심하고 합리적인 가격으로 구매하여,\r\n");
      out.write("          <br>아름다운 작품으로부터 느끼는 행복과 함께 다양한 경제적 수익을 올릴 수 있습니다.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cont2\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"txt\">\r\n");
      out.write("        <h1>02</h1>\r\n");
      out.write("        <h2>역량 있는 작가들이 창작활동에만\r\n");
      out.write("          <br>  집중할 수 있도록 전시 홍보, 렌탈 및 판매에\r\n");
      out.write("          <br>   이르기까지 모든 지원을 아끼지 않습니다.\r\n");
      out.write("         \r\n");
      out.write("        </h2>\r\n");
      out.write("        <p>현재의 국내 미술 시장은 대형 갤러리에서 소수의 유명 작가들의 작품들만\r\n");
      out.write("          <br>유통이 되고 있는 시장입니다. 갤러리K는 역량 있는 작가들을 발굴하여\r\n");
      out.write("          <br> 경제적인 걱정을 하지 않고 창작활동에만 집중할 수 있도록 전시, 홍보,\r\n");
      out.write("          <br> 렌탈 및 판매에 필요한 모든 서비스를 지원합니다.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cont3\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"txt\">\r\n");
      out.write("        <h1>03\r\n");
      out.write("             \r\n");
      out.write("        </h1>\r\n");
      out.write("        <h2>한국 미술의 부흥과 세계화를 꿈꿉니다.\r\n");
      out.write("          \r\n");
      out.write("        </h2>\r\n");
      out.write("        <p>아름다운 미술품은 생활의 여유와 내면의 평화를 줍니다.\r\n");
      out.write("          <br>갤러리K는 미술과 경제의 통합을 통하여 한국미술시장의 대중화를 실현합니다.\r\n");
      out.write("          <br>갤러리K와 함께하면, 많은 사람들은 자신이 구입한 미술품을 감상하는 정도에서 머물지 않고 경제적 이익을 얻을 수 있고,\r\n");
      out.write("          <br>많은 작가들은 작품의 홍보와 판매를 걱정하지 않고 창작활동에만 집중할 수 있습니다.\r\n");
      out.write("          <br>이처럼 한국미술시장의 대중화를 실현함으로써, 한국 미술의 부흥을 넘어 K-POP과 같은 세계화를 꿈꿉니다.\r\n");
      out.write("          \r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div> <!-- #wrap -->\r\n");
      out.write("<footer>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
