/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-08-13 05:08:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduceArtists_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>작가 소개</title>\r\n");
      out.write("	<script src=\"script/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("	<script src=\"script/header.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/introduceArtists.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <h1><a href=\"#\"><img src=\"img/header.png\" alt=\"갤러리익선\"></a></h1>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#\">Gallery</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"introduce.jsp\">Gallery Iksun 소개</a></li>\r\n");
      out.write("                    <li><a href=\"introduceArtists.jsp\">작가별 보기</a></li>\r\n");
      out.write("                    <li><a href=\"thema.jsp\">테마별 보기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"shop.jsp\">미술품 구매</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"shop.jsp\">원화 구입</a></li>\r\n");
      out.write("                    <li><a href=\"wishlist.jsp\">장바구니</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"community.jsp\">커뮤니티</a>\r\n");
      out.write("                <!-- <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"community.jsp\">게시판</a></li>\r\n");
      out.write("                </ul> -->\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"mypage.jsp\">마이페이지</a>\r\n");
      out.write("                <ul class=\"sub\">\r\n");
      out.write("                    <li><a href=\"myorder.jsp\">주문확인</a></li>\r\n");
      out.write("                    <li><a href=\"mypage.jsp\">개인정보확인</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"right\">\r\n");
      out.write("        <a href=\"signIn.jsp\">로그인</a>\r\n");
      out.write("        <a href=\"signUp.jsp\">회원가입</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"h_bg\"></div>\r\n");
      out.write("</header>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("    <h1>작가 소개</h1>\r\n");
      out.write("    <div class=\"contents\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                  \r\n");
      out.write("                    <div class=\"f_img\"><a href=\"writer01.jsp\"><img src=\"img/artist_jks.jpg\" alt=\"조경심\"></a></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>소정 조경심</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>개인전 10회</p>\r\n");
      out.write("                        <p>(사)한국미술협회 문인화분과 부이사장</p>\r\n");
      out.write("                        <p>(사)한국미술협회 초대작가</p>\r\n");
      out.write("                        <p>대한민국미술대전 운영, 심사위원 역임</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"writer02.jsp\"><img src=\"img/artist_shs.jpg\" alt=\"서혜숙\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>운정 서혜숙</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>개인전 1회, 회원전 다수</p>\r\n");
      out.write("                        <p>대한민국미술대전 문인화부문 초대작가</p>\r\n");
      out.write("                        <p>(사)한국미술협회 문인화분과 이사</p>\r\n");
      out.write("                        <p>대한민국경기미술대전, 명인미술대전, 서예문인화대전 심사위원 역임</p>                 \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"writer03.jsp\"><img src=\"img/artist_phj.jpg\" alt=\"박호자\"></a></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>혜진 박호자</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>대한민국미술대전 문인화부문 우수상, 초대작가</p>\r\n");
      out.write("                        <p>경기미술문인화대전 우수상, 초대작가</p>\r\n");
      out.write("                        <p>성남전통미술대전 대상, 초대작가</p>\r\n");
      out.write("                        <p>한국예술문화원 문체부장관상, 초대작가</p>\r\n");
      out.write("                        <p>경기미술문인화대전 2차 심사위원 역임</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_02.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("             <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"writer04.jsp\"><img src=\"img/artist_pjw.jpg\" alt=\"박중욱\"></a></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>효천 박중욱</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>대한민국미술대전 문인화부문 초대작가</p>\r\n");
      out.write("                        <p>경기미술문인화대전 초대작가</p>\r\n");
      out.write("                        <p>한국예술문화원 초대작가(서울시장상, 최우수상)</p>\r\n");
      out.write("                        <p>한국미술협회 문인화 분과위원</p>\r\n");
      out.write("                        <p>한국예술문화원 심사위원</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>  \r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"writer05.jsp\"><img src=\"img/artist_ksh.jpg\" alt=\"권상학\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>와석 권상학</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>(사)한국미술협회 문인화부문 초대작가</p>\r\n");
      out.write("                        <p>한국예술문화원 초대작가</p>\r\n");
      out.write("                        <p>광화문광장 휘호대회 대상</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_02.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"writer06.jsp\"><img src=\"img/artist_jkh.jpg\" alt=\"정경화\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>소윤 정경화</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>대한민국서예문인화대전 초대작가</p>\r\n");
      out.write("                        <p>대한민국통일명인미술대전 초대작가</p>\r\n");
      out.write("                        <p>대한민국경기미술대전 우수상</p>\r\n");
      out.write("                        <p>광화문광장휘호대회 문체부장관상</p>\r\n");
      out.write("                        <p>대한민국미술대전 특선</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"#\"><img src=\"img/artist_jya.jpg\" alt=\"주영애\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>소연 주영애</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>대한민국서예문인화대전 초대작가</p>\r\n");
      out.write("                        <p>대한민국통일명인미술대전 초대작가</p>\r\n");
      out.write("                        <p>대한민국경기미술대전 입선, 특선</p>\r\n");
      out.write("                        <p>광화문광장휘호대회 문체부장관상</p>\r\n");
      out.write("                        <p>대한민국미술대전 입선, 특선</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"#\"><img src=\"img/artist_neh.jpg\" alt=\"노은희\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>소담 노은희</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>통일명인미술대전 초대작가</p>\r\n");
      out.write("                        <p>대한민국서예문인화대전 초대작가(우수상)</p>\r\n");
      out.write("                        <p>경기미술문인화대전 특선</p>\r\n");
      out.write("                        <p>대한민국미술대전 문인화부문 입선</p>\r\n");
      out.write("                        <p>광화문광장휘호대회 한글학회장상</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"#\"><img src=\"img/artist_kyj.jpg\" alt=\"김용재\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>온일 김용재</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>문인화정신전 출품</p>\r\n");
      out.write("                        <p>통일명인미술대전 초대작가</p>\r\n");
      out.write("                        <p>서예문인화대전 삼체상</p>\r\n");
      out.write("                        <p>경기미술문인화대전 특선</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("           \r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"#\"><img src=\"img/artist_khn.jpg\" alt=\"김해니\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>해니 김해니</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>문인화정신전 출품</p>\r\n");
      out.write("                        <p>통일명인미술대전 삼체상</p>\r\n");
      out.write("                        <p>서예문인화대전 삼체상</p>\r\n");
      out.write("                        <p>경기미술문인화대전 입선</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"#\"><img src=\" \" alt=\"최지향\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>지향 최지향</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>문인화정신전 출품</p>\r\n");
      out.write("                        <p>통일명인미술대전 삼체상</p>\r\n");
      out.write("                        <p>서예문인화대전 삼체상</p>\r\n");
      out.write("                        <p>경기미술문인화대전 입선</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"f_img\"><a href=\"#\"><img src=\" \" alt=\"이보석\"></a></div>\r\n");
      out.write("                    <div class=\"txt\">\r\n");
      out.write("                        <h3>보석 이보석</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                        <p>문인화정신전 출품</p>\r\n");
      out.write("                        <p>통일명인미술대전 삼체상</p>\r\n");
      out.write("                        <p>서예문인화대전 삼체상</p>\r\n");
      out.write("                        <p>경기미술문인화대전 입선</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bg\" style=\"background-image: url(img/image_01.jpg);\"> </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li> -->\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div><!-- .contents -->\r\n");
      out.write("</div> <!-- #wrap -->\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
