/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-08-15 09:41:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>작가 소개</title>\r\n");
      out.write("        <script src=\"script/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("        <script src=\"script/header.js\"></script>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/shop_product.css\">         \r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <header>\r\n");
      out.write("            <h1><a href=\"#\"><img src=\"img/header.png\" alt=\"갤러리익선\"></a></h1>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">Gallery</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"introduce.jsp\">Gallery Iksun 소개</a></li>\r\n");
      out.write("                            <li><a href=\"introduceArtists.jsp\">작가별 보기</a></li>\r\n");
      out.write("                       <!-- <li><a href=\"thema.jsp\">테마별 보기</a></li> -->    \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"shop.jsp\">미술품 구매</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"shop.jsp\">원화 구입</a></li>\r\n");
      out.write("                            <li><a href=\"wishlist.jsp\">장바구니</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"community.jsp\">커뮤니티</a>\r\n");
      out.write("                        <!-- <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"community.jsp\">게시판</a></li>\r\n");
      out.write("                        </ul> -->\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"mypage.jsp\">마이페이지</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"myorder.jsp\">주문확인</a></li>\r\n");
      out.write("                            <li><a href=\"mypage.jsp\">개인정보확인</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"right\">\r\n");
      out.write("                <a href=\"signIn.jsp\">로그인</a>\r\n");
      out.write("                <a href=\"signUp.jsp\">회원가입</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bg\"></div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <div id=\"wrap\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <h1>원화 구입</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"product\">\r\n");
      out.write("                <div class=\"pic\">\r\n");
      out.write("                    <img src=\"img/2019_jks_sunflower.jpg\" alt=\"해바라기\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                    <div class=\"p_title\">\r\n");
      out.write("                        <p>해바라기</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>작가명</th>\r\n");
      out.write("                            <td>조경심</td>\r\n");
      out.write("                            <th>작품번호</th>\r\n");
      out.write("                            <td>00001</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>작품크기</th>\r\n");
      out.write("                            <td>70X70</td>\r\n");
      out.write("                            <th>재료</th>\r\n");
      out.write("                            <td>장지에채색</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"price\">\r\n");
      out.write("                            <th>가격(원)</th>\r\n");
      out.write("                            <td colspan=\"3\">5,000,000</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div class=\"btns\">\r\n");
      out.write("                        <input type=\"button\" value=\"바로구매\">    \r\n");
      out.write("                        <input type=\"button\" value=\"장바구니\">    \r\n");
      out.write("                        <input type=\"button\" value=\"위시리스트\"> \r\n");
      out.write("                        <input type=\"button\" value=\"공유하기\">   \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>                            \r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <h1>작가 소개</h1>\r\n");
      out.write("            <div class=\"desc_artist\">\r\n");
      out.write("                <div class=\"a_pic\">\r\n");
      out.write("                    <img src=\"img/artist_jks.jpg\" alt=\"조경심\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"a_intro\">\r\n");
      out.write("                    <p class=\"a_name\">조경심</p>\r\n");
      out.write("                    <p>개인전 10회</p>\r\n");
      out.write("                    <p>(사)한국미술협회 문인화분과 부이사장</p>\r\n");
      out.write("                    <p>(사)한국미술협회 초대작가</p>\r\n");
      out.write("                    <p>대한민국미술대전 운영, 심사위원 역임</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"order_process\">\r\n");
      out.write("                <h1>작품 구매 및 배송안내</h1>\r\n");
      out.write("                <div class=\"steps\">\r\n");
      out.write("                    <h2>미술품 구매 계약 체결</h2>\r\n");
      out.write("                    <p>홈페이지를 통해 작품을 구매하고 결제를 합니다.</p>\r\n");
      out.write("                    <p>작품을 배송받을 주소를 입력합니다.</p>\r\n");
      out.write("                    <p>결제 익일에 미술품 구매계약서를 전자계약서로 발송합니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"caution\">\r\n");
      out.write("                    <h2>배송 관련 유의사항</h2>\r\n");
      out.write("                    <p>공휴일 제외, 영업일 기준 2-3일 이내 배송기사님께서 고객님께 연락을 드립니다.</p>\r\n");
      out.write("                    <p>배송 후, 단순 변심으로 인한 반품은 불가합니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <footer>\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("        </footer>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
